---
server:
  port: 9001
spring:
  config.activate.on-profile: default
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
solace:
  hostUrl: "tcps://mr-connection-qhgik3f2ezp.messaging.solace.cloud:55443"
  vpnName: "montrealbroker-10-1"
  userName: "solace-cloud-client"
  password: "3cp5luj5jrcu9776rrlt0dos20"
  reconnectionAttempts: "20"
  connectionRetriesPerHost: "5"
  salesOrderQueueName: "SalesOrderReEnrichedQueue"
  businessPartnerQueueName: "businessPartnerReEnrichedQueue"
  notificationQueueName: "notificationReEnrichedQueue"
  materialMasterQueueName: "materialMasterReEnrichedQueue"
  chartOfAccountsQueueName: "chartOfAccountsReEnrichedQueue"